### PR TITLE
Add questions

### PR DESCRIPTION
**Pull request by Kundan28**
@mozzadrella, could you please help me with this question?

### CODE REVIEW

**Comment by ericdrosado** [comment]
Hi @Kundan28! There are a lot of pros and cons to using a GUI versus the CLI. Personally I would recommend the CLI because you can customize your experience. If you are new to Git, I would recommend trying both. Some GUI's have helpful interfaces that can help you to learn Git. Ultimately the decision comes down to your needs in your workflow. Find something that not only brings you joy when you work, but that will allow you to work effectively.

**Comment by Kundan28** [comment]
Thanks for the clarification. Should I merge this PR now ?

**Comment by ericdrosado** [comment]
Feel free to merge.

**Comment by Kundan28** [comment]
I am having one doubt that I have was not able to add @mozzadrella a reviewer.

**Comment by ericdrosado** [comment]
No worries, I am conducting reviews for @mozzadrella for Campus Advisors.

If you are concerned about adding someone as a reviewer for future PR's 
Screen Shot 2019-04-04 at 10 45 18 AM
Notice in the top right corner of this image that there is a section where you can add reviewers.

For now, you are OK to move forward with your training.

**Comment by Kundan28** [comment]
When when I tried to add reviewer and mentioned @mozzadrella nothing popped up.

**Comment by ericdrosado** [comment]
This is most likely due to the fact that she was not added as a "collaborator" to your project. 

Here is an article on the subject:

https://help.github.com/en/articles/inviting-collaborators-to-a-personal-repository

If you want to test it out, add me as a reviewer, by adding me as a collaborator first.

**Comment by Kundan28** [comment]
Okay, I got it.
Thanks for the help.
One last query is that how much would it take rest of the task to be verified to become Campus Advisor and when will I get the response for that certificate for which I filled the form today.

**Comment by ericdrosado** [comment]
Currently we are working through a backlog of teachers that are interested in receiving certification. An email will be sent soon regarding scheduling interviews. We thank you for your patience.

**Comment by Kundan28** [comment]
Okay, thanks!

**Comment by Kundan28** [comment]
Hope to hear within a week.

**Pull request merged**
